---
#-------------------------------
# General Site Settings
title: Andrew's Dev
logo: # You can add own logo. For example '/images/logo.png'.
description: Java, Spring, MySQL Backend Blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://umanking.github.io" # the base hostname & protocol for your site, e.g. http://example.com
blog-theme: light # By default, Atega theme uses a 'light' color scheme, to change the color scheme to dark use 'dark' value (_includes/color-scheme)
locale: "ko-KR"

#-------------------------------
# Author Settings
author:
  name: Andrew
  image: "/images/01.jpg"

#-------------------------------
# Hero Settings
hero:
  hero__title: Hi! I'm <span class="hero__name">Andrew</span>
  hero__job: BackEnd Developer
  hero__description: #Java, Spring, Database, IntelliJ Lover
  hero__button__text: Read about my past
  hero__button__link: "/about"
  hero__image: "/images/01.jpg"

#-------------------------------
# Newsletter (_includes/footer-widgets/widget-subscribe.html)
mailchimp__title: Subscribe to new posts # Add your Title
mailchimp__text: Subscribe to our newsletter and we’ll send you the emails of latest posts. # Add your description.
mailchimp__identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
mailchimp__button__text: Subscribe # Add your button text

#-------------------------------
# Contact Settings
contact:
  email: umanking@gmail.com # Add your email for contant form
  description: Atega 한글인경우에 comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want. # Add a description of your form

# NOTE
# Atega comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.

#-------------------------------
# Social Links (Footer)
# Example of adding a new link to the footer - {icon: "ion-logo-facebook", link: "https://facebook.com"}
# Other icons can be found at https://ionicons.com/v4/
social:
  # - { icon: "ion-logo-twitter", link: "https://twitter.com" }
  - { icon: "ion-logo-github", link: "https://github.com/umanking" }
  # - { icon: "ion-logo-youtube", link: "https://youtube.com" }
  # - { icon: "ion-logo-pinterest", link: "https://pinterest.com" }
  # - { icon: "ion-logo-codepen", link: "https://codepen.io" }
  # - { icon: "ion-logo-vimeo", link: "https://vimeo.com/" }
  - { icon: "ion-logo-linkedin", link: "https://www.linkedin.com/in/umanking/" }


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: umanking # add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Gallery Footer Section
gallery:
  title: Gallery
  images:
    - alt: "Minimalism"
      url: "/images/06.jpg"
    - alt: "Minimalism"
      url: "/images/05.jpg"
    - alt: "Minimalism"
      url: "/images/08.jpg"
    - alt: "Minimalism"
      url: "/images/03.jpg"
    - alt: "Minimalism"
      url: "/images/09.jpg"
    - alt: "Minimalism"
      url: "/images/04.jpg"

#-------------------------------
# Google Analytics
google-analytics: G-YQEVSKEF43 # Add your identifier. For example UA-99631805-1.

#-------------------------------
# Build Settings
markdown: kramdown
# highlighter: rouge
kramdown:
  # input: GFM
  highlighter: rouge
  syntax_highlighter_opts:
    block:
        line_numbers: false

permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  # - jekyll-feed
  - jekyll/tagging
  - jekyll-compose
  - jekyll-seo-tag
  # - jekyll-toc

paginate: 15
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: "_pages"
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir: tag
tag_page_layout: tag_page
tag_permalink_style: /:title

sass:
  sass_dir: _sass
  style: compressed

jekyll_compose:
  auto_open: true
  default_front_matter:
    posts:
      toc: true
      tags: []
      categories: []
      image: ""
      description: 

# feed:
  # path: feed.xml
  # posts_limit: 50
  # tags: true
